version: "3"

services:
  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=gobarber
      - POSTGRES_PASSWORD=gobarber

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

volumes:
  postgres:
  mongo:
  redis: